version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh

  web:
    build: .
    command: >
      bash -c "sed -i 's/\r$//' /app/start_playwright_server.sh && 
             chmod +x /app/start_playwright_server.sh &&
             python -c 'from app import create_app; app = create_app(); app.app_context().push(); from app import db; db.create_all()' && 
             waitress-serve --port=5000 --call app:create_app"
    volumes:
      - .:/app
      - ./data:/app/data
      - playwright_browsers:/app/ms-playwright
    ports:
      - "5000:5000"
    devices:
      - /dev/random:/dev/random
      - /dev/urandom:/dev/urandom
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
      - REDIS_URL=redis://redis:6379
      - DOCKER_ENV=true
      - TZ=Asia/Ho_Chi_Minh
      - PLAYWRIGHT_SERVER_URL=http://playwright-server:11435
      - PLAYWRIGHT_BROWSERS_PATH=/app/ms-playwright
    depends_on:
      - redis
      - playwright-server
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  rq-worker:
    build: .
    command: >
      bash -c "set -e &&
             sed -i 's/\r$//' /app/start_playwright_server.sh && 
             chmod +x /app/start_playwright_server.sh &&
             echo 'Installing Playwright browsers' &&
             python -m playwright install chromium &&
             echo 'Starting worker and Playwright server' &&
             bash /app/start_playwright_server.sh & 
             sleep 14 &&
             python -m rq.cli worker default --url redis://redis:6379 --worker-class app.WindowsSimpleWorker --with-scheduler --verbose"
    volumes:
      - .:/app
      - ./data:/app/data
      - playwright_browsers:/app/ms-playwright
    devices:
      - /dev/random:/dev/random
      - /dev/urandom:/dev/urandom
    environment:
      - REDIS_URL=redis://redis:6379
      - DOCKER_ENV=true
      - PYTHONUNBUFFERED=1
      - PLAYWRIGHT_BROWSERS_PATH=/app/ms-playwright
      - TZ=Asia/Ho_Chi_Minh
      - PLAYWRIGHT_SERVER_URL=http://playwright-server:11435
    depends_on:
      - redis
      - playwright-server
      - web
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  playwright-server:
    image: node:20
    working_dir: /app/mcp_server/playwright-custom-server
    command: sh -c "npm install && npx playwright install-deps && npx playwright install && npm start"
    volumes:
      - .:/app
    ports:
      - "11435:11435"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - NODE_OPTIONS=--max_old_space_size=4096
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11435/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 2G

volumes:
  redis_data:
  playwright_browsers: 