"""empty message

Revision ID: 7cdff76e99b3
Revises: 
Create Date: 2025-05-05 00:08:24.728949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cdff76e99b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('website_id', sa.Integer(), nullable=True),
    sa.Column('check_history_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.Column('included_in_summary', sa.Boolean(), nullable=True),
    sa.Column('summary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['check_history_id'], ['check_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['website.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
